#pragma once
// AnimSetDataYaml — animationsetdatasinglefile.txt as a decomposed FOLDER (the ".txt/" tree).
//
// The monolithic set-data cache decomposes into a folder carrying its own name+extension, the
// same convention a "<name>.hkx" behavior decomposes into a "<name>.hkx/" folder:
//
//     meshes/animationsetdatasinglefile.txt/
//       index.yaml            project ORDER + exact header strings (the file's line-1 manifest)
//       movesets/<stem>.yaml  AUTHORED: each project's sets (gate / equip / attacks)
//       crcs/<stem>.yaml      BAKED residue: each set's path-CRC registrations (un-reversible)
//
// The split is "author what reverses, bake what doesn't": gate/equip/attacks round-trip to YAML
// and are hand-editable; the CRC membership block is opaque game data (a path hash the engine
// matches loaded animations against — 5% don't even reverse to a roster name), so it ships
// VERBATIM as a baked sibling — a trivial identity round-trip that keeps the whole compose
// byte-exact. New mod content needs no baked CRCs: the servers derive them from the authored
// animation paths (TripleForAnimation). `<stem>` is the lowercased basename of the project
// header ("ChickenProjectData\ChickenProject.txt" -> "chickenproject").
//
// Assemble(index + movesets + crcs) -> EmitSingleFile reproduces vanilla byte-for-byte; that
// round-trip is the drift gate (havok-core-cli setdata-tree-roundtrip). Shared by the converter
// (decompose) and the runtime (ServeSetData composes the base from this folder) — ryml-gated.

#include "havok/anim/AnimationSetData.h"

#include <map>
#include <string>
#include <vector>

namespace havok::animsetdata {

    // One project's sets -> movesets.yaml text (authoring intent only; CRCs live in crcs.yaml).
    std::string EmitMovesetsYaml(const Project& project);

    // movesets.yaml -> a SingleFile carrying ONE project (header derived from `projectName`,
    // e.g. "DefaultMale" -> "DefaultMaleData\DefaultMale.txt"). Sets carry gate/equip/attacks
    // with EMPTY crcs (Assemble fills them from crcs.yaml; mod deltas derive them). Never throws —
    // malformed input leaves `err` set and returns whatever parsed.
    SingleFile ParseMovesetsYaml(const std::string& text, const std::string& projectName,
                                 std::string& err);

    // ── The ".txt/" folder pieces ────────────────────────────────────────────────
    // The lowercased basename-stem of a project header ("ChickenProjectData\ChickenProject.txt"
    // -> "chickenproject") — the key the movesets/ and crcs/ files are named by.
    std::string StemForHeader(const std::string& header);

    // index.yaml: the project ORDER + exact header strings (the .txt's leading count + list).
    // This is the one piece neither authored nor derivable — the engine indexes projects by it.
    std::string              EmitSetdataIndexYaml(const SingleFile& sf);
    std::vector<std::string> ParseSetdataIndexYaml(const std::string& text, std::string& err);

    // crcs.yaml: the BAKED residue — each set name (no ".txt") -> its CRC triples, in order.
    // Opaque game data, regenerated by the converter, not hand-edited.
    std::string EmitSetdataCrcsYaml(const Project& project);
    std::map<std::string, std::vector<CrcTriple>> ParseSetdataCrcsYaml(const std::string& text,
                                                                       std::string& err);

    // Stitch the decomposed folder back into a SingleFile, in index order. `headers` gives the
    // project order + exact header strings; `movesetsByStem` supplies each project's sets (order
    // authoritative); `crcsByStem` supplies the baked registrations, matched to sets by name. A
    // header absent from movesetsByStem yields a zero-set project (still emitted, from the index);
    // a set absent from crcsByStem keeps empty CRCs. EmitSingleFile on the result reproduces the
    // vanilla .txt byte-for-byte when the three pieces are the vanilla decompose.
    SingleFile AssembleSetdata(
        const std::vector<std::string>& headers,
        const std::map<std::string, SingleFile>& movesetsByStem,
        const std::map<std::string, std::map<std::string, std::vector<CrcTriple>>>& crcsByStem);

}  // namespace havok::animsetdata
