# EmbedEnums.cmake — generate GeneratedEnums.cpp (compiled-in enum tables) from the schema's
# enum data tree Havok/core/Schema/enums/*.yaml. The yaml is the single hand-edited source; this
# bakes it into the DLL at build time so HavokEnums.h holds no hardcoded tables.
#
# Invoked as a script:  cmake -DENUM_DIR=<dir> -DOUT_CPP=<file> -P EmbedEnums.cmake
#
# The enum yaml is a small, fixed shape (name:/flags:/items: with `- { name: X , value: N }`),
# so a line-oriented regex parse here is sufficient and keeps codegen tool-free (no build-time
# Python/CLI dependency, no dependency cycle into havok-framing).

if(NOT DEFINED ENUM_DIR OR NOT DEFINED OUT_CPP)
    message(FATAL_ERROR "EmbedEnums.cmake: ENUM_DIR and OUT_CPP are required")
endif()

file(GLOB _files "${ENUM_DIR}/*.yaml")
list(SORT _files)   # deterministic output order

set(_arrays "")
set(_registry "")
set(_n 0)

foreach(_f IN LISTS _files)
    file(READ "${_f}" _txt)

    # enum type name — the top-level `name:` (item `name:`s are all preceded by `{`)
    string(REGEX MATCH "name:[ ]*([A-Za-z0-9_]+)" _ "${_txt}")
    set(_name "${CMAKE_MATCH_1}")
    if(NOT _name)
        message(FATAL_ERROR "EmbedEnums.cmake: no 'name:' in ${_f}")
    endif()

    string(REGEX MATCH "flags:[ ]*(true|false)" _ "${_txt}")
    set(_flags "${CMAKE_MATCH_1}")
    if(NOT _flags)
        set(_flags "false")
    endif()

    # each item: `{ name: IDENT , value: -?N }`
    string(REGEX MATCHALL "{[ ]*name:[ ]*[A-Za-z0-9_]+[ ]*,[ ]*value:[ ]*-?[0-9]+[ ]*}" _items "${_txt}")
    set(_arr "")
    set(_count 0)
    foreach(_it IN LISTS _items)
        string(REGEX MATCH "name:[ ]*([A-Za-z0-9_]+)[ ]*,[ ]*value:[ ]*(-?[0-9]+)" _ "${_it}")
        string(APPEND _arr "    {\"${CMAKE_MATCH_1}\", ${CMAKE_MATCH_2}},\n")
        math(EXPR _count "${_count}+1")
    endforeach()

    string(APPEND _arrays "static const GenItem A${_n}[] = {\n${_arr}};\n")
    string(APPEND _registry "    {\"${_name}\", ${_flags}, A${_n}, ${_count}},\n")
    math(EXPR _n "${_n}+1")
endforeach()

set(_body
"// GENERATED by cmake/EmbedEnums.cmake from Havok/core/Schema/enums/*.yaml -- DO NOT EDIT.
// The yaml data tree is the single source; this bakes it into the binary. Regenerated at build
// whenever an enum yaml changes. Backs havok::model::enums::EnumTable (see HavokEnums.h).
#include <havok/model/HavokEnums.h>
#include <string>
#include <unordered_map>

namespace havok::model::enums {
namespace {
struct GenItem { const char* name; long value; };
struct GenEnum { const char* name; bool isFlags; const GenItem* items; int count; };

${_arrays}
static const GenEnum kAll[] = {
${_registry}};
} // namespace

const std::unordered_map<std::string, long>& EnumTable(const std::string& name) {
    static const std::unordered_map<std::string, std::unordered_map<std::string, long>> kCache = [] {
        std::unordered_map<std::string, std::unordered_map<std::string, long>> c;
        for (const auto& e : kAll) {
            auto& m = c[e.name];
            for (int i = 0; i < e.count; ++i) m[e.items[i].name] = e.items[i].value;
        }
        return c;
    }();
    static const std::unordered_map<std::string, long> kEmpty;
    auto it = kCache.find(name);
    return it == kCache.end() ? kEmpty : it->second;
}
} // namespace havok::model::enums
")

file(WRITE "${OUT_CPP}" "${_body}")
